### ISSUE TITLE
There are identical sub-expressions

### ISSUE THREAD

**Issue by thehlopster** [NMan1/external-warzone-cheat#1]
https://github.com/NMan1/external-warzone-cheat/blob/520884a23d24712c6aeee03edf36f9c78e770022/modern_warfare/core/utils/vectors.h#L45

it looks like copy paste error, should be probably replaced with:
```cpp
 return (x == v.x) && (y == v.y) && (z == v.z); 
```

**Comment by NMan1** [comment]
fixed
