### ISSUE TITLE
Is this detected and if so what to change

### ISSUE THREAD

**Issue by vatosyorgos** [NMan1/external-warzone-cheat#11]
On Issue #8 the user uBadRequest said about this project "I ended up getting banned so quick".

To my understanding Warzone has '_mainly_' an userlevel AC, i thought using RPM and WPM through an Kernel should bypass the AC easily, but it looks like iam missing something.

Is this something basic like the AC detecting this by signature checking or is the AC more capable than i thought?

Iam reading couple Threads on UC and other sites about Kernel developing but still struggle to understand more complex topics like hiding a Driver from the AC. (Currently Ive only done basic game hacking like a cs go external)

**What would I have to do to make it undetected** (only for personal use)?

**Comment by NMan1** [comment]
Cheat is probaly siged and scanned for by their ac but if you change a few things that wouldn’t matter. 

I’d say probably the overlay method is the reason as that’s the only user mode component. I don’t follow the game anymore so I’m not entirely sure if they’ve changed or updated any detection methods.

**Comment by vatosyorgos** [comment]
I was using this to write my own RadarTool (not as an overlay, a completely own external Tool for second screen) and would have changed the Driver-Project a bit and would have rewritten most of the Client-Project. Iam mainly to scared about WPM~
Atleast the signature check wouldnt be a problem this way.

"I don’t follow the game anymore so I’m not entirely sure if they’ve changed or updated any detection methods."
So my next step should be digging into the AC right?

**Comment by NMan1** [comment]
I wouldn’t bother reversing their anti cheat. Unless they’ve added a kernel component (which they haven’t), the driver in the project should be fine. If you just want to use the method included for reading and writing you more then likely should be completely safe.

**Comment by vatosyorgos** [comment]
Alright thank you, iam gonna close this Issue.

**Comment by anzenchitai** [comment]
> Alright thank you, iam gonna close this Issue.

well if you're talking about writing bytes to uav you should be completely fine

**Comment by vatosyorgos** [comment]
> 
> well if you're talking about writing bytes to uav you should be completely fine

No my plan was not to use any WPM, iam not advanced enough yet to understand everything about the AntiCheats. I always wondered why they cant/wont just scan values that changed for no reason (like the uav-flag) and mayb flag for that. If possible i would try to stay undetected for the longest time.

So thats why iam going to do a simple External RadarTool where I draw dots on x and y coordinates.

**Comment by anzenchitai** [comment]
> > well if you're talking about writing bytes to uav you should be completely fine
> 
> No my plan was not to use any WPM, iam not advanced enough yet to understand everything about the AntiCheats. I always wondered why they cant/wont just scan values that changed for no reason (like the uav-flag) and mayb flag for that. If possible i would try to stay undetected for the longest time.
> 
> So thats why iam going to do a simple External RadarTool where I draw dots on x and y coordinates.

ring 0 wpm uav is undetected for years but if they implement a new anticheat that would be game changing
