### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by Tipsymario3** [NMan1/external-warzone-cheat#12]
Compiled everything with the offsets that were updated by vinicius and with uc offsets to try but nothing works. The log shows up normally with all of the correct things but no esp in game. I mapped the driver before starting the game and opened modernwarfareclient in a plunder game but nothing actually shows in game.

**Comment by NMan1** [comment]
Send a picture of the printed offsets. More than likely something is wrong. Perhaps the overlay broke as well. Debug and step through code etc.

**Comment by anzenchitai** [comment]
you sure the decryption is updated as well?

**Comment by anzenchitai** [comment]
the offsets he updated are completely wrong and the decryption is ancient

**Comment by NMan1** [comment]
And that’s why it wasn’t working
