### ISSUE TITLE
i have not find PID when i open

### ISSUE THREAD

**Issue by thangdvt1** [NMan1/external-warzone-cheat#4]
i have not find PID when i open. can u help me. tks
![image](https://user-images.githubusercontent.com/83772660/123566960-416ed100-d7eb-11eb-90cf-9e5710ccb81d.png)

**Comment by smuggood** [comment]
same here , i have a AMD GPU and this is what i get

**Comment by ArkaIison** [comment]
Hi, i've the same problem ! I use nvidia graphic card (1060) and intel processor

**Comment by ArkaIison** [comment]
Hi ! I've the same problem ! I use nvidia graphic card and intel processor

**Comment by NMan1** [comment]
You guys are just not loading it properly. Use the included kdmapper with the driver. If that kdmapper blue screens you then find another one that fits your windows version. The game must also be open when you launch the file, how else will it find the game.

**Comment by ArkaIison** [comment]
Do you know any KDMAPPER for winver 20H2, because no one work, i think it's come from there ^^

**Comment by NMan1** [comment]
The one included in the repo works on 20H2 (19042.928)
