### ISSUE TITLE
failed to find client_info_base

### ISSUE THREAD

**Issue by Singh-Kiran-P** [NMan1/external-warzone-cheat#9]
![image](https://user-images.githubusercontent.com/13298319/125203369-66962180-e278-11eb-94bb-6f4e09096f44.png)
I am getting this after a use 
   - kd.exe modern_warfare_driver.sys
   - then opened modern_warfare_client.exe

**Comment by NMan1** [comment]
[“offsets are not up to date”](https://github.com/NMan1/external-warzone-cheat#offsests-are-not-up-to-date)
